import CustomModal from "../../../components/CustomModal";
import "../../../design/scss/prospect-modal.scss";
import "../../../design/scss/modal-designs.scss";
import "../../../design/scss/form-designs.scss";
import "../../../design/scss/pages/report-management/ReportManagement.scss";

export function ViewReportModal({ showModal, closeModal }) {
    if (!showModal) return null;

    const renderHeader = () => (
        <>
            <h1 className="modal-title">View Report Details</h1>
            <button
                type="button"
                className="btn-close"
                aria-label="Close"
                onClick={closeModal}
            ></button>
        </>
    );

    const renderBody = () => (
        <div className="modal-body">
            <div className="view-vessel-container">
                {/* ROW 1 — Report Name + Report Type + Call Type */}
                <div className="view-row">
                    <div className="view-item">
                        <div className="view-label">Report Name</div>
                        <div className="view-value">{showModal.reportName || "-"}</div>
                    </div>
                    <div className="view-item">
                        <div className="view-label">Report Type</div>
                        <div className="view-value">{showModal.reportType || "-"}</div>
                    </div>
                    <div className="view-item">
                        <div className="view-label">Call Type</div>
                        <div className="view-value">
                            {showModal.callType ? (
                                <span
                                    className={`report-call-type-badge report-call-type-badge--${showModal.callType.toLowerCase()}`}
                                >
                                    {showModal.callType}
                                </span>
                            ) : "-"}
                        </div>
                    </div>
                </div>

                {/* ROW 2 — Generated Date + Generated By + Status */}
                <div className="view-row">
                    <div className="view-item">
                        <div className="view-label">Generated Date</div>
                        <div className="view-value">{showModal.generatedDate || "-"}</div>
                    </div>
                    <div className="view-item">
                        <div className="view-label">Generated By</div>
                        <div className="view-value">{showModal.generatedBy || "-"}</div>
                    </div>
                    <div className="view-item">
                        <div className="view-label">Status</div>
                        <div className="view-value">{showModal.status || "-"}</div>
                    </div>
                </div>

                {/* ROW 3 — Format + Size + Description */}
                <div className="view-row">
                    <div className="view-item">
                        <div className="view-label">Format</div>
                        <div className="view-value">{showModal.format || "-"}</div>
                    </div>
                    <div className="view-item">
                        <div className="view-label">Size</div>
                        <div className="view-value">{showModal.size || "-"}</div>
                    </div>
                    <div className="view-item">
                        <div className="view-label">Description</div>
                        <div className="view-value">{showModal.description || "-"}</div>
                    </div>
                </div>
            </div>
        </div>
    );

    return (
        <CustomModal
            dialgName="modal-dialog modal-dialog-centered"
            show={!!showModal}
            closeModal={() => closeModal(null)}
            body={renderBody()}
            header={renderHeader()}
        />
    );
}
