import { useState } from "react";
import { RenderAction } from "./RenderCells";
import CommonHeader from "../../components/CommonHeader";
import CustomTable from "../../components/customTable";
import { ViewReportModal } from "./Modals/ViewReport";
import "../../design/scss/pages/report-management/ReportManagement.scss";

const initialReports = [
    {
        _id: "1",
        reportName: "Monthly Operations Report",
        reportType: "Operations",
        generatedDate: "2024-01-15",
        generatedBy: "Admin User",
        status: "Completed",
        format: "PDF",
        size: "2.5 MB",
        description: "Monthly operations summary",
    },
    {
        _id: "2",
        reportName: "Crew Attendance Report",
        reportType: "Crew",
        generatedDate: "2024-01-14",
        generatedBy: "HR Manager",
        status: "Completed",
        format: "Excel",
        size: "1.2 MB",
        description: "Crew attendance for January",
    },
    {
        _id: "3",
        reportName: "Vessel Inspection Report",
        reportType: "Inspection",
        generatedDate: "2024-01-13",
        generatedBy: "Inspector",
        status: "Pending",
        format: "PDF",
        size: "3.1 MB",
        description: "Vessel inspection results",
    },
    {
        _id: "4",
        reportName: "Financial Summary",
        reportType: "Finance",
        generatedDate: "2024-01-12",
        generatedBy: "Finance Team",
        status: "Completed",
        format: "PDF",
        size: "4.8 MB",
        description: "Q4 financial summary",
    },
    {
        _id: "5",
        reportName: "Port Activity Log",
        reportType: "Operations",
        generatedDate: "2024-01-11",
        generatedBy: "Port Manager",
        status: "Completed",
        format: "CSV",
        size: "0.9 MB",
        description: "Daily port activities",
    },
    {
        _id: "6",
        reportName: "Maintenance Schedule",
        reportType: "Maintenance",
        generatedDate: "2024-01-10",
        generatedBy: "Maintenance Team",
        status: "In Progress",
        format: "Excel",
        size: "1.5 MB",
        description: "Monthly maintenance schedule",
    },
    {
        _id: "7",
        reportName: "Safety Compliance Report",
        reportType: "Safety",
        generatedDate: "2024-01-09",
        generatedBy: "Safety Officer",
        status: "Completed",
        format: "PDF",
        size: "2.3 MB",
        description: "Safety compliance checklist",
    },
    {
        _id: "8",
        reportName: "Inventory Status",
        reportType: "Inventory",
        generatedDate: "2024-01-08",
        generatedBy: "Warehouse Manager",
        status: "Completed",
        format: "Excel",
        size: "1.8 MB",
        description: "Current inventory levels",
    },
];

const ReportManagement = () => {
    const [reports] = useState(initialReports);
    const [viewModal, setViewModal] = useState(null);

    const [params, setParams] = useState({
        page: 1,
        total: 0,
        limit: 10,
        searchTerm: '',
        sortOrder: -1,
        sortBy: 'reportName',
    });

    const cols = [
        {
            name: 'Report Name',
            selector: 'reportName',
            tableClasses: 'table-striped',
            contentClass: 'table-content',
            sort: true,
            thclass: 'tb-head',
            width: '200',
        },
        {
            name: 'Report Type',
            selector: 'reportType',
            tableClasses: 'table-striped',
            sort: true,
            contentClass: 'table-content',
            thclass: 'tb-head',
            width: '150',
        },
        {
            name: 'Generated Date',
            selector: 'generatedDate',
            tableClasses: 'table-striped',
            sort: true,
            contentClass: 'table-content',
            thclass: 'tb-head',
            width: '150',
        },
        {
            name: 'Generated By',
            selector: 'generatedBy',
            tableClasses: 'table-striped',
            sort: true,
            contentClass: 'table-content',
            thclass: 'tb-head',
            width: '150',
        },
        {
            name: 'Status',
            selector: 'status',
            tableClasses: 'table-striped',
            sort: true,
            contentClass: 'table-content',
            thclass: 'tb-head',
            width: '120',
        },
        {
            name: 'Format',
            selector: 'format',
            tableClasses: 'table-striped',
            sort: true,
            contentClass: 'table-content',
            thclass: 'tb-head',
            width: '100',
        },
        {
            name: 'Size',
            selector: 'size',
            tableClasses: 'table-striped',
            sort: true,
            contentClass: 'table-content',
            thclass: 'tb-head',
            width: '100',
        },
        {
            name: 'Description',
            selector: 'description',
            tableClasses: 'table-striped',
            sort: true,
            contentClass: 'table-content',
            thclass: 'tb-head',
            width: '200',
        },
        {
            name: 'Action',
            selector: 'action',
            tableClasses: 'table-striped',
            contentClass: 'table-content',
            thclass: 'tb-head',
            cell: (props) => <RenderAction {...props} onViewClick={handleViewClick} />,
            width: '100',
            notView: true,
        },
    ];

    const handleViewClick = (row) => {
        setViewModal(row);
    };

    return (
        <>
            <div className="page-body">
                <div className="prospect employee">
                    <div className="container-fluid">
                        <CommonHeader
                            tableTitle="Report Management"
                            isAddEnabled={false}
                            addModalLabel="Add Report"
                            setSearch={(e) =>
                                setParams({ ...params, searchTerm: e, page: 1, limit: 10 })
                            }
                            exportTitle="Export"
                            exportLoader={false}
                        />
                    </div>

                    <CustomTable
                        pagination={{ currentPage: params?.page, limit: params?.limit }}
                        tableClasses="px-start"
                        count={reports.length}
                        columns={cols}
                        data={reports ?? []}
                        onPageChange={(currentPage) =>
                            setParams({ ...params, page: currentPage })
                        }
                        setLimit={(newlimit) => setParams({ ...params, limit: newlimit })}
                        onSorting={(sortBy) => {
                            setParams({
                                ...params,
                                sortBy,
                                sortOrder: params?.sortOrder === -1 ? 1 : -1,
                                page: 1,
                            });
                        }}
                        onView={handleViewClick}
                    />
                </div>
            </div>

            {!!viewModal && (
                <ViewReportModal
                    showModal={viewModal}
                    closeModal={() => setViewModal(null)}
                />
            )}
        </>
    );
};

export default ReportManagement;

