// Role-based route permissions configuration
// Roles: 1-Super Admin (legacy/mock), 2-Admin, 3-Port Admin, 4-Port Operator,
// 5-Port Manager, 6-Vendor, 7-Finance in lists below — API may assign Super Admin as role_id "7"
import { ROUTE_PATHS } from "./paths";

export const ROLE_IDS = {
  SUPER_ADMIN: "1",
  ADMIN: "2",
  PORT_ADMIN: "3",
  PORT_OPERATOR: "4",
  PORT_MANAGER: "5",
  VENDOR: "6",
  FINANCE: "7",
  CEO: "23",
};

/** Super Admin from API (role_name "Super Admin"); bypasses routePermissions like SUPER_ADMIN "1" */
export const SUPER_ADMIN_API_ROLE_ID = "7";

/** DA (role_id 22 in this environment's actual data, not ROLE_IDS.*); bypasses
 * routePermissions the same as SUPER_ADMIN/VENDOR, per explicit user confirmation. */
const DA_API_ROLE_ID = "22";

const hasUnrestrictedRouteAccess = (userRoleId) =>
  userRoleId === ROLE_IDS.SUPER_ADMIN ||
  userRoleId === SUPER_ADMIN_API_ROLE_ID ||
  userRoleId === ROLE_IDS.VENDOR ||
  userRoleId === DA_API_ROLE_ID;

// Define all routes with their allowed roles
export const routePermissions = {
  [ROUTE_PATHS.DASHBOARD]: [ROLE_IDS.SUPER_ADMIN, ROLE_IDS.ADMIN, ROLE_IDS.PORT_ADMIN, ROLE_IDS.CEO, ROLE_IDS.PORT_OPERATOR, ROLE_IDS.PORT_MANAGER, ROLE_IDS.VENDOR, ROLE_IDS.FINANCE],
  "/kanban-board": [ROLE_IDS.SUPER_ADMIN, ROLE_IDS.ADMIN, ROLE_IDS.PORT_ADMIN, ROLE_IDS.CEO, ROLE_IDS.PORT_OPERATOR, ROLE_IDS.PORT_MANAGER, ROLE_IDS.VENDOR],
  "/kanban-board/operator": [ROLE_IDS.SUPER_ADMIN, ROLE_IDS.ADMIN, ROLE_IDS.PORT_ADMIN, ROLE_IDS.CEO, ROLE_IDS.PORT_OPERATOR, ROLE_IDS.PORT_MANAGER, ROLE_IDS.VENDOR],
  "/compact": [ROLE_IDS.SUPER_ADMIN, ROLE_IDS.ADMIN, ROLE_IDS.PORT_ADMIN, ROLE_IDS.CEO, ROLE_IDS.PORT_OPERATOR, ROLE_IDS.PORT_MANAGER, ROLE_IDS.VENDOR],
  "/workspaces": [ROLE_IDS.SUPER_ADMIN, ROLE_IDS.ADMIN, ROLE_IDS.PORT_ADMIN, ROLE_IDS.CEO, ROLE_IDS.PORT_OPERATOR, ROLE_IDS.PORT_MANAGER, ROLE_IDS.VENDOR],
  "/edit-workflow": [ROLE_IDS.SUPER_ADMIN, ROLE_IDS.ADMIN, ROLE_IDS.PORT_ADMIN, ROLE_IDS.CEO, ROLE_IDS.VENDOR],
  "/roles": [ROLE_IDS.SUPER_ADMIN, ROLE_IDS.ADMIN],
  "/permissions": [ROLE_IDS.SUPER_ADMIN, ROLE_IDS.ADMIN, ROLE_IDS.PORT_ADMIN, ROLE_IDS.CEO],
  "/users": [ROLE_IDS.SUPER_ADMIN, ROLE_IDS.ADMIN, ROLE_IDS.PORT_ADMIN, ROLE_IDS.CEO],
  "/port-management": [ROLE_IDS.SUPER_ADMIN, ROLE_IDS.ADMIN, ROLE_IDS.PORT_ADMIN, ROLE_IDS.CEO],
  "/vessel-types": [ROLE_IDS.SUPER_ADMIN, ROLE_IDS.ADMIN, ROLE_IDS.PORT_ADMIN, ROLE_IDS.CEO, ROLE_IDS.PORT_OPERATOR, ROLE_IDS.VENDOR],
  "/barge-types": [ROLE_IDS.SUPER_ADMIN, ROLE_IDS.ADMIN, ROLE_IDS.PORT_ADMIN, ROLE_IDS.CEO, ROLE_IDS.PORT_OPERATOR, ROLE_IDS.VENDOR],
  "/vessel-onboarding": [ROLE_IDS.SUPER_ADMIN, ROLE_IDS.ADMIN, ROLE_IDS.PORT_ADMIN, ROLE_IDS.CEO, ROLE_IDS.PORT_OPERATOR, ROLE_IDS.VENDOR],
  "/billing-entity": [ROLE_IDS.SUPER_ADMIN, ROLE_IDS.ADMIN, ROLE_IDS.PORT_ADMIN, ROLE_IDS.CEO, ROLE_IDS.FINANCE],
  "/customer-pricing": [ROLE_IDS.SUPER_ADMIN, ROLE_IDS.ADMIN, ROLE_IDS.PORT_ADMIN, ROLE_IDS.CEO, ROLE_IDS.FINANCE],
  "/customer-pricing-infobhan": [ROLE_IDS.SUPER_ADMIN, ROLE_IDS.ADMIN, ROLE_IDS.PORT_ADMIN, ROLE_IDS.CEO, ROLE_IDS.FINANCE],
  "/custom-inspection": [ROLE_IDS.SUPER_ADMIN, ROLE_IDS.ADMIN, ROLE_IDS.PORT_ADMIN, ROLE_IDS.CEO, ROLE_IDS.PORT_OPERATOR, ROLE_IDS.PORT_MANAGER, ROLE_IDS.VENDOR],
  "/crew-management": [ROLE_IDS.SUPER_ADMIN, ROLE_IDS.ADMIN, ROLE_IDS.PORT_ADMIN, ROLE_IDS.CEO, ROLE_IDS.PORT_OPERATOR, ROLE_IDS.PORT_MANAGER, ROLE_IDS.VENDOR],
  "/report-management": [ROLE_IDS.SUPER_ADMIN, ROLE_IDS.ADMIN, ROLE_IDS.PORT_ADMIN, ROLE_IDS.CEO, ROLE_IDS.PORT_MANAGER, ROLE_IDS.FINANCE],
  "/activity-log": [ROLE_IDS.SUPER_ADMIN, ROLE_IDS.ADMIN, ROLE_IDS.PORT_ADMIN, ROLE_IDS.CEO, ROLE_IDS.PORT_MANAGER],
  "/notification": [ROLE_IDS.SUPER_ADMIN, ROLE_IDS.ADMIN, ROLE_IDS.PORT_ADMIN, ROLE_IDS.CEO, ROLE_IDS.PORT_OPERATOR, ROLE_IDS.PORT_MANAGER, ROLE_IDS.VENDOR, ROLE_IDS.FINANCE],
  "/appointment-acceptance": [ROLE_IDS.SUPER_ADMIN, ROLE_IDS.ADMIN, ROLE_IDS.PORT_ADMIN, ROLE_IDS.CEO, ROLE_IDS.PORT_OPERATOR, ROLE_IDS.PORT_MANAGER, ROLE_IDS.VENDOR],
  "/pre-arrival-information": [ROLE_IDS.SUPER_ADMIN, ROLE_IDS.ADMIN, ROLE_IDS.PORT_ADMIN, ROLE_IDS.CEO, ROLE_IDS.PORT_OPERATOR, ROLE_IDS.PORT_MANAGER, ROLE_IDS.VENDOR],
  "/driver-management": [ROLE_IDS.SUPER_ADMIN, ROLE_IDS.ADMIN, ROLE_IDS.PORT_ADMIN, ROLE_IDS.CEO, ROLE_IDS.PORT_OPERATOR, ROLE_IDS.VENDOR],
  "/vehicle-management": [ROLE_IDS.SUPER_ADMIN, ROLE_IDS.ADMIN, ROLE_IDS.PORT_ADMIN, ROLE_IDS.CEO, ROLE_IDS.PORT_OPERATOR, ROLE_IDS.VENDOR],
  "/driver-vehicle-mapping": [ROLE_IDS.SUPER_ADMIN, ROLE_IDS.ADMIN, ROLE_IDS.PORT_ADMIN, ROLE_IDS.CEO, ROLE_IDS.PORT_OPERATOR, ROLE_IDS.VENDOR],
  "/time-objects": [ROLE_IDS.SUPER_ADMIN, ROLE_IDS.ADMIN, ROLE_IDS.PORT_ADMIN, ROLE_IDS.CEO, ROLE_IDS.PORT_OPERATOR, ROLE_IDS.VENDOR],
  "/stage-time-mappings": [ROLE_IDS.SUPER_ADMIN, ROLE_IDS.ADMIN, ROLE_IDS.PORT_ADMIN, ROLE_IDS.CEO, ROLE_IDS.PORT_OPERATOR, ROLE_IDS.VENDOR],
  "/check-list": [ROLE_IDS.SUPER_ADMIN, ROLE_IDS.ADMIN, ROLE_IDS.PORT_ADMIN, ROLE_IDS.CEO, ROLE_IDS.PORT_OPERATOR, ROLE_IDS.PORT_MANAGER, ROLE_IDS.VENDOR],
  "/hotel-management": [ROLE_IDS.SUPER_ADMIN, ROLE_IDS.ADMIN, ROLE_IDS.PORT_ADMIN, ROLE_IDS.CEO, ROLE_IDS.PORT_OPERATOR, ROLE_IDS.VENDOR],
  "/material-type": [ROLE_IDS.SUPER_ADMIN, ROLE_IDS.ADMIN, ROLE_IDS.PORT_ADMIN, ROLE_IDS.CEO, ROLE_IDS.PORT_OPERATOR, ROLE_IDS.VENDOR],
  "/packing-type": [ROLE_IDS.SUPER_ADMIN, ROLE_IDS.ADMIN, ROLE_IDS.PORT_ADMIN, ROLE_IDS.CEO, ROLE_IDS.PORT_OPERATOR, ROLE_IDS.VENDOR],
  "/logistics-warehouse": [ROLE_IDS.SUPER_ADMIN, ROLE_IDS.ADMIN, ROLE_IDS.PORT_ADMIN, ROLE_IDS.CEO, ROLE_IDS.PORT_OPERATOR, ROLE_IDS.VENDOR],
  "/order-history": [ROLE_IDS.SUPER_ADMIN, ROLE_IDS.ADMIN, ROLE_IDS.PORT_ADMIN, ROLE_IDS.CEO, ROLE_IDS.PORT_OPERATOR, ROLE_IDS.VENDOR],
  "/document-checklist": [ROLE_IDS.SUPER_ADMIN, ROLE_IDS.ADMIN, ROLE_IDS.PORT_ADMIN, ROLE_IDS.CEO, ROLE_IDS.PORT_OPERATOR, ROLE_IDS.PORT_MANAGER, ROLE_IDS.VENDOR],
  "/status-management": [ROLE_IDS.SUPER_ADMIN, ROLE_IDS.ADMIN, ROLE_IDS.PORT_ADMIN, ROLE_IDS.CEO, ROLE_IDS.PORT_OPERATOR, ROLE_IDS.PORT_MANAGER, ROLE_IDS.VENDOR],
  "/custom-fields": [ROLE_IDS.SUPER_ADMIN, ROLE_IDS.ADMIN, ROLE_IDS.PORT_ADMIN, ROLE_IDS.CEO, ROLE_IDS.VENDOR],
  "/job-status": [ROLE_IDS.SUPER_ADMIN, ROLE_IDS.ADMIN, ROLE_IDS.PORT_ADMIN, ROLE_IDS.CEO, ROLE_IDS.PORT_OPERATOR, ROLE_IDS.PORT_MANAGER, ROLE_IDS.VENDOR],
  "/group-email": [ROLE_IDS.SUPER_ADMIN, ROLE_IDS.ADMIN, ROLE_IDS.PORT_ADMIN, ROLE_IDS.CEO, ROLE_IDS.PORT_OPERATOR, ROLE_IDS.VENDOR],
  "/billing-instruction": [ROLE_IDS.SUPER_ADMIN, ROLE_IDS.ADMIN, ROLE_IDS.PORT_ADMIN, ROLE_IDS.CEO, ROLE_IDS.FINANCE],
  "/captains": [ROLE_IDS.SUPER_ADMIN, ROLE_IDS.ADMIN, ROLE_IDS.PORT_ADMIN, ROLE_IDS.CEO, ROLE_IDS.PORT_OPERATOR, ROLE_IDS.PORT_MANAGER, ROLE_IDS.VENDOR],
  "/fleet": [ROLE_IDS.SUPER_ADMIN, ROLE_IDS.ADMIN, ROLE_IDS.PORT_ADMIN, ROLE_IDS.CEO, ROLE_IDS.PORT_OPERATOR, ROLE_IDS.PORT_MANAGER, ROLE_IDS.VENDOR],
  [ROUTE_PATHS.OPERATORS]: [ROLE_IDS.SUPER_ADMIN, ROLE_IDS.ADMIN, ROLE_IDS.PORT_ADMIN, ROLE_IDS.CEO, ROLE_IDS.PORT_OPERATOR, ROLE_IDS.PORT_MANAGER, ROLE_IDS.VENDOR],
  [ROUTE_PATHS.MWP_HISTORY]: [ROLE_IDS.SUPER_ADMIN, ROLE_IDS.ADMIN, ROLE_IDS.PORT_ADMIN, ROLE_IDS.CEO, ROLE_IDS.PORT_OPERATOR, ROLE_IDS.PORT_MANAGER, ROLE_IDS.VENDOR],
  "/lh-services": [ROLE_IDS.SUPER_ADMIN, ROLE_IDS.ADMIN, ROLE_IDS.PORT_ADMIN, ROLE_IDS.CEO, ROLE_IDS.PORT_OPERATOR, ROLE_IDS.PORT_MANAGER, ROLE_IDS.VENDOR],
  "/transport-company": [ROLE_IDS.SUPER_ADMIN, ROLE_IDS.ADMIN, ROLE_IDS.PORT_ADMIN, ROLE_IDS.CEO, ROLE_IDS.PORT_OPERATOR, ROLE_IDS.PORT_MANAGER, ROLE_IDS.VENDOR],
  "/hospital-management": [ROLE_IDS.SUPER_ADMIN, ROLE_IDS.ADMIN, ROLE_IDS.PORT_ADMIN, ROLE_IDS.CEO, ROLE_IDS.PORT_OPERATOR, ROLE_IDS.PORT_MANAGER, ROLE_IDS.VENDOR],
  "/medical-services": [ROLE_IDS.SUPER_ADMIN, ROLE_IDS.ADMIN, ROLE_IDS.PORT_ADMIN, ROLE_IDS.CEO, ROLE_IDS.PORT_OPERATOR, ROLE_IDS.PORT_MANAGER, ROLE_IDS.VENDOR],
  "/hospital-services": [ROLE_IDS.SUPER_ADMIN, ROLE_IDS.ADMIN, ROLE_IDS.PORT_ADMIN, ROLE_IDS.CEO, ROLE_IDS.PORT_OPERATOR, ROLE_IDS.PORT_MANAGER, ROLE_IDS.VENDOR],
  "/third-party-service": [ROLE_IDS.SUPER_ADMIN, ROLE_IDS.ADMIN, ROLE_IDS.PORT_ADMIN, ROLE_IDS.CEO, ROLE_IDS.PORT_OPERATOR, ROLE_IDS.PORT_MANAGER, ROLE_IDS.VENDOR],
  "/crew-template": [ROLE_IDS.SUPER_ADMIN, ROLE_IDS.ADMIN, ROLE_IDS.PORT_ADMIN, ROLE_IDS.CEO, ROLE_IDS.PORT_OPERATOR, ROLE_IDS.PORT_MANAGER, ROLE_IDS.VENDOR],
  "/kpi-dashboard": [ROLE_IDS.SUPER_ADMIN, ROLE_IDS.ADMIN, ROLE_IDS.PORT_ADMIN, ROLE_IDS.CEO, ROLE_IDS.PORT_OPERATOR, ROLE_IDS.PORT_MANAGER, ROLE_IDS.VENDOR, ROLE_IDS.FINANCE],
  "/kpi-tasks": [ROLE_IDS.SUPER_ADMIN, ROLE_IDS.ADMIN, ROLE_IDS.PORT_ADMIN, ROLE_IDS.CEO, ROLE_IDS.PORT_OPERATOR, ROLE_IDS.PORT_MANAGER, ROLE_IDS.VENDOR, ROLE_IDS.FINANCE],
  "/kpi-users": [ROLE_IDS.SUPER_ADMIN, ROLE_IDS.ADMIN, ROLE_IDS.PORT_ADMIN, ROLE_IDS.CEO, ROLE_IDS.PORT_OPERATOR, ROLE_IDS.PORT_MANAGER, ROLE_IDS.VENDOR, ROLE_IDS.FINANCE],
  "/da-module": [ROLE_IDS.SUPER_ADMIN, ROLE_IDS.ADMIN, ROLE_IDS.PORT_ADMIN, ROLE_IDS.CEO, ROLE_IDS.PORT_OPERATOR, ROLE_IDS.PORT_MANAGER, ROLE_IDS.VENDOR],
  "/vendor-portal/dashboard": [ROLE_IDS.SUPER_ADMIN, ROLE_IDS.ADMIN, ROLE_IDS.PORT_ADMIN, ROLE_IDS.CEO, ROLE_IDS.PORT_OPERATOR, ROLE_IDS.PORT_MANAGER, ROLE_IDS.VENDOR, ROLE_IDS.FINANCE],
  "/vendor-portal/invoices": [ROLE_IDS.SUPER_ADMIN, ROLE_IDS.ADMIN, ROLE_IDS.PORT_ADMIN, ROLE_IDS.CEO, ROLE_IDS.PORT_OPERATOR, ROLE_IDS.PORT_MANAGER, ROLE_IDS.VENDOR, ROLE_IDS.FINANCE],
  "/vendor-portal/orders": [ROLE_IDS.SUPER_ADMIN, ROLE_IDS.ADMIN, ROLE_IDS.PORT_ADMIN, ROLE_IDS.CEO, ROLE_IDS.PORT_OPERATOR, ROLE_IDS.PORT_MANAGER, ROLE_IDS.VENDOR, ROLE_IDS.FINANCE],
  "/location": [ROLE_IDS.SUPER_ADMIN, ROLE_IDS.ADMIN, ROLE_IDS.PORT_ADMIN, ROLE_IDS.CEO, ROLE_IDS.PORT_OPERATOR, ROLE_IDS.VENDOR],
  "/service-providers": [ROLE_IDS.SUPER_ADMIN, ROLE_IDS.ADMIN, ROLE_IDS.PORT_ADMIN, ROLE_IDS.CEO, ROLE_IDS.PORT_OPERATOR, ROLE_IDS.VENDOR],
  "/transport-parties": [ROLE_IDS.SUPER_ADMIN, ROLE_IDS.ADMIN, ROLE_IDS.PORT_ADMIN, ROLE_IDS.CEO, ROLE_IDS.PORT_OPERATOR, ROLE_IDS.VENDOR],
  "/waste-types": [ROLE_IDS.SUPER_ADMIN, ROLE_IDS.ADMIN, ROLE_IDS.PORT_ADMIN, ROLE_IDS.CEO, ROLE_IDS.PORT_OPERATOR, ROLE_IDS.VENDOR],
  "/settings": [ROLE_IDS.SUPER_ADMIN, ROLE_IDS.ADMIN, ROLE_IDS.PORT_ADMIN, ROLE_IDS.CEO],
  // CEO email-approval deep link — CEO-only. Without this entry, hasRouteAccess's
  // "unlisted route = allow" fallback let any logged-in user reach the Approve
  // action by navigating to the URL directly.
  "/approval/ceo": [ROLE_IDS.CEO],
};

// Helper function to check if a role has access to a route
export const hasRouteAccess = (userRoleId, routePath) => {
  if (hasUnrestrictedRouteAccess(userRoleId)) {
    return true;
  }

  // First, try exact match
  let allowedRoles = routePermissions[routePath];

  // If no exact match, check if routePath starts with any base route
  // This handles dynamic routes like /kanban-board/123 or /kanban-board/123/analytics
  if (!allowedRoles) {
    // Find matching base route by checking if routePath starts with any route in routePermissions
    const matchingRoute = Object.keys(routePermissions).find(baseRoute => {
      // Match exact route or route with trailing path segments
      // e.g., /kanban-board matches /kanban-board/123 or /kanban-board/123/analytics
      return routePath === baseRoute || routePath.startsWith(baseRoute + '/');
    });

    if (matchingRoute) {
      allowedRoles = routePermissions[matchingRoute];
    }
  }

  if (!allowedRoles) {
    return true; // Do not block valid app routes that are missing from config
  }

  return allowedRoles.includes(userRoleId);
};

// Get all allowed routes for a role
export const getAllowedRoutesForRole = (userRoleId) => {
  if (hasUnrestrictedRouteAccess(userRoleId)) {
    return Object.keys(routePermissions); // All routes
  }

  return Object.keys(routePermissions).filter(route =>
    routePermissions[route].includes(userRoleId)
  );
};
